name: Sync Shopping Subtree

on:
  schedule:
    - cron: '0 3 * * *' # 매일 새벽 3시에 자동 실행
  workflow_dispatch: # 수동 실행 버튼도 생성

jobs:
  sync-subtree:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout homework repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Setup Git identity
        run: |
          git config user.name "이도윤"
          git config user.email "dlwhdgus482@naver.com"

      - name: Add react-study remote
        run: |
          git remote remove react-study || true
          git remote add react-study https://github.com/DoYoonDev/react-study.git
          git fetch react-study

      - name: Pull subtree
        env:
          GIT_COMMITTER_NAME: "이도윤"
          GIT_COMMITTER_EMAIL: "dlwhdgus482@naver.com"
          GIT_AUTHOR_NAME: "이도윤"
          GIT_AUTHOR_EMAIL: "dlwhdgus482@naver.com"
        run: |
          git subtree pull --prefix=shopping react-study main --squash

      - name: Push changes
        run: |
          git push origin main