name: Sync Subtree from react-study

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout homework repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Set up Git identity
        run: |
          git config --global user.name "이도윤"
          git config --global user.email "dlwhdgus482@naver.com"

      - name: Add react-study remote
        run: |
          git remote add react-study https://github.com/DoYoonDev/react-study.git
          git fetch react-study

      - name: Pull subtree from react-study/shopping
        run: |
          git subtree pull --prefix=shopping react-study main --squash

      - name: Push to homework repo
        run: |
          git push origin main